/// <reference path="../typings/tsd.d.ts"/>
/// <reference path="../config/config.ts" />
/// <reference path="../config/box2d.ts" />
/// <reference path="../config/controls.ts" />
/// <reference path="../config/keys.ts" />
/// <reference path="../managers/asset.ts" />
/// <reference path="../objects/asset.ts" />
/// <reference path="../objects/label.ts" />
/// <reference path="../objects/button.ts" />
/// <reference path="../objects/scene.ts" />
/// <reference path="../objects/scoreboard.ts" />
/// <reference path="../objects/reality.ts" />
/// <reference path="../objects/platform.ts" />
/// <reference path="../objects/exitdoor.ts" />
/// <reference path="../objects/hero.ts" />
/// <reference path="../objects/enemy.ts" />
/// <reference path="../objects/coin.ts" />
/// <reference path="../scenes/gameover.ts" />
/// <reference path="../scenes/menu.ts" />
/// <reference path="../scenes/level.ts" /> 

//# sourceMappingURL=_references.js.map
